coverage:
    reports:
        - html
        - text
    exclude:
        - app/Console/Kernel.php
        - app/Exceptions/Handler.php
        - app/Http/Kernel.php
        - app/Providers/AppServiceProvider.php
        - app/Providers/AuthServiceProvider.php
        - app/Providers/EventServiceProvider.php
        - app/Providers/RouteServiceProvider.php
        - bootstrap/*
        - config/*
        - database/*
        - resources/*
        - routes/*
        - storage/*
        - tests/*
